[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

authors = ["dionysus"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.21", features = ["derive"] }
